apiVersion: v1
kind: Service
metadata:
  name: nextcast-api
  namespace: production
  labels:
    app: nextcast-api
spec:
  type: ClusterIP
  selector:
    app: nextcast-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
